apiVersion: v1
kind: Service
metadata:
  name: mpc-api-svc
  namespace: lux-mpc
  labels:
    app: mpc-api
    app.kubernetes.io/part-of: lux-mpc
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: api
  selector:
    app: mpc-api
